/*
|| Creates generic view DEALER instead of the one provided by LHS
|| The main point is exclusion of the table PARTY_ROLE - dealer are selected
|| from CUSTOMER_ROLE by using specific PARTY_TYPE_ID. If ever the value
|| changes (which is quite unlikely as it is baseline setup), the view
|| should be recreated. Provides huge performance gains
|| $Log: dealer.sql,v $
|| Revision 1.1.1.1  2011/02/15 15:30:28  shmyg
|| All Maroc Telecom project files after reorganization
||
*/

CREATE	OR REPLACE VIEW sysadm.dealer
AS
SELECT	ca.customer_id,
	ca.customer_id_high,
	ca.custcode,
	ca.csst,
	ca.cstype,
	ca.csactivated,
	ca.csdeactivated,
	ca.cstype_date,
	ca.cslevel,
	ca.cscusttype,
	ca. cslvlname,
	ca.tmcode,
	ca.prgcode,
	ca.csclimit,
	ca.cscurbalance,
	ca.csdepdate,
	ca.cstestbillrun,
	ca.bill_layout,
	ca.paymntresp,
	ca.target_reached,
	ca.pcsmethpaymnt,
	ca.passportno,
	ca.birthdate,
	ca.dunning_flag,
	ca.comm_no,
	ca. pos_comm_type,
	ca.btx_password,
	ca.btx_user,
	ca.settles_p_month,
	ca.cashretour,
	ca.cstradecode,
	ca.cspassword,
	ca.cspromotion,
	ca.cscompregno,
	ca.cscomptaxno,
	ca.csreason,
	ca.cscollector,
	ca.cscontresp,
	ca.csdeposit,
	ca.cscredit_date,
	ca.cscredit_remark,
	ca.suspended,
	ca.reactivated,
	ca.prev_balance,
	ca.lbc_date,
	ca.employee,
	ca.company_type,
	ca.crlimit_exc,
	ca.area_id,
	ca.costcenter_id,
	ca.csfedtaxid,
	ca.credit_rating,
	ca.cscredit_status,
	ca.deact_create_date,
	ca.deact_receip_date,
	ca.edifact_addr,
	ca.edifact_user_flag,
	ca.edifact_flag,
	ca.csdeposit_due_date,
	ca.calculate_deposit,
	ca.tmcode_date,
	ca.csrentalbc,
	ca.id_type,
	ca.user_lastmod,
	ca.csentdate,
	ca.csmoddate,
	ca.csmod,
	ca.csnationality,
	ca.customer_id_ext,
	ca.csclimit_o_tr1,
	ca.csclimit_o_tr2,
	ca.csclimit_o_tr3,
	ca.cscredit_score,
	ca.cstraderef,
	ca.cssocialsecno,
	ca.csdrivelicence,
	ca.cssex,
	ca.csemployer,
	ca.wpid,
	ca.csprepayment,
	ca.csremark_1,
	ca.csremark_2,
	ca.bill_information,
	ca.dealer_id,
	ca.dunning_mode,
	ca.not_valid,
	ca.cscrdcheck_agreed,
	ca.marital_status,
	ca.expect_pay_curr_id,
	ca.convratetype_payment,
	ca.refund_curr_id,
	ca.convratetype_refund,
	ca.srcode,
	ca.currency,
	ca.rec_version,
	ca.anonymous_customer,
	ca.external_customer_id,
	ca.external_customer_set_id,
	ca.custnum,
	ca.business_unit_id,
	ca.party_type_id,
	ca.individual_overdisc_flag,
	ca.billing_threshold,
	ca.billing_threshold_currency,
	ca.threshold_billing_mode,
	ca.threshold_billing_purpose,
	ca.created_by_user
FROM	customer_role cr,
	customer_all  ca
-- This is a generic view. Created to improve performance
-- instead of the original one provided by LHS
WHERE	cr.customer_id = ca.customer_id
AND	cr.party_role_id = 14
AND	NVL(CSMOD, 'X') != 'D'
WITH	CHECK OPTION
/
