ALTER TABLESPACE temp ADD TEMPFILE '/u04/oradata/bscspp/temp_02.dbf' SIZE 8G AUTOEXTEND OFF;
ALTER TABLESPACE temp ADD TEMPFILE '/u04/oradata/bscspp/temp_03.dbf' SIZE 8G AUTOEXTEND OFF;
ALTER TABLESPACE temp ADD TEMPFILE '/u04/oradata/bscspp/temp_04.dbf' SIZE 8G AUTOEXTEND OFF;
ALTER TABLESPACE temp ADD TEMPFILE '/u04/oradata/bscspp/temp_05.dbf' SIZE 8G AUTOEXTEND OFF;
ALTER TABLESPACE temp ADD TEMPFILE '/u04/oradata/bscspp/temp_06.dbf' SIZE 8G AUTOEXTEND OFF;
