CREATE	TABLESPACE d_prepaid
DATAFILE	'/u08/oradata/bscs9mig/d_prepaid_01.dbf' SIZE 8G AUTOEXTEND OFF,
		'/u08/oradata/bscs9mig/d_prepaid_02.dbf' SIZE 8G AUTOEXTEND OFF
EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
