revoke execute on utl_file from to public;
revoke execute on utl_tcp from to public;
revoke execute on utl_http from to public;
revoke execute on utl_smtp from to public;
revoke execute on dbms_random from to public;
grant execute on utl_file to dbsnmp;
grant execute on utl_file to mgmt_user;
grant execute on utl_file to sysman;
grant execute on utl_file to xdb;
grant execute on utl_file to ordsys;
grant execute on utl_file to ORDPLUGINS;
grant execute on utl_file to olapsys;
grant execute on utl_file to mdsys;
grant execute on utl_file to wmsys;
grant execute on utl_file utl_tcp to dbsnmp;
grant execute on utl_file to mgmt_user;
grant execute on utl_file to sysman;
grant execute on utl_http to dbsnmp;
grant execute on utl_http to mgmt_user;
grant execute on utl_http to sysman;
grant execute on utl_http to ORDPLUGINS;
grant execute on utl_http to mdsys;
grant execute on utl_smtp to dbsnmp;
grant execute on utl_smtp to mgmt_user;
grant execute on utl_smtp to sysman;
grant execute on dbms_random to dbsnmp;
grant execute on dbms_random to mgmt_user;
grant execute on dbms_random to sysman;
grant execute on dbms_random to mdsys;
grant execute on dbms_lob to dbsnmp;
grant execute on dbms_lob to mgmt_user;
grant execute on dbms_lob to sysman;
grant execute on dbms_lob to xdb;
grant execute on dbms_lob to ctxsys;
grant execute on dbms_lob to ordsys;
grant execute on dbms_lob to ORDPLUGINS;
grant execute on dbms_lob to mdsys;
grant execute on dbms_lob to olapsys;
grant execute on dbms_lob to exfsys;
grant execute on dbms_job to dbsnmp;
grant execute on dbms_job to mgmt_user;
grant execute on dbms_job to sysman;
grant execute on dbms_job to xdb;
