CREATE	USER SYSADM
IDENTIFIED BY sysadm
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP;
 
GRANT SELECT ANY DICTIONARY TO SYSADM WITH ADMIN OPTION;
 
GRANT CREATE MATERIALIZED VIEW TO SYSADM;
 
GRANT CREATE TRIGGER TO SYSADM;
 
GRANT EXECUTE ANY PROCEDURE TO SYSADM;
 
GRANT ALTER ANY PROCEDURE TO SYSADM;
 
GRANT CREATE PROCEDURE TO SYSADM;
 
GRANT CREATE ROLE TO SYSADM;
 
GRANT DROP PUBLIC DATABASE LINK TO SYSADM;
 
GRANT CREATE PUBLIC DATABASE LINK TO SYSADM;
 
GRANT CREATE DATABASE LINK TO SYSADM;
 
GRANT CREATE SEQUENCE TO SYSADM;
 
GRANT CREATE VIEW TO SYSADM;
 
GRANT DROP PUBLIC SYNONYM TO SYSADM;
 
GRANT CREATE PUBLIC SYNONYM TO SYSADM;
 
GRANT CREATE SYNONYM TO SYSADM;
 
GRANT SELECT ANY TABLE TO SYSADM;
 
GRANT CREATE TABLE TO SYSADM;
 
GRANT DROP USER TO SYSADM WITH ADMIN OPTION;
 
GRANT ALTER USER TO SYSADM WITH ADMIN OPTION;
 
GRANT CREATE USER TO SYSADM WITH ADMIN OPTION;
 
GRANT UNLIMITED TABLESPACE TO SYSADM WITH ADMIN OPTION;
 
GRANT ALTER SESSION TO SYSADM WITH ADMIN OPTION;
 
GRANT CREATE SESSION TO SYSADM WITH ADMIN OPTION;
 
GRANT CONNECT TO SYSADM WITH ADMIN OPTION;
 
GRANT RESOURCE TO SYSADM WITH ADMIN OPTION;
 
GRANT EXECUTE_CATALOG_ROLE TO SYSADM;
 
GRANT EXP_FULL_DATABASE TO SYSADM;
 
GRANT IMP_FULL_DATABASE TO SYSADM;
 
GRANT BSCS_ROLE TO SYSADM WITH ADMIN OPTION;
 
-- new object type path is: SCHEMA_EXPORT/DEFAULT_ROLE
ALTER USER SYSADM DEFAULT ROLE ALL;
