ALTER TABLESPACE temp ADD TEMPFILE '/u04/oradata/bscs9r1/temp_02.dbf' SIZE 8G AUTOEXTEND OFF;
ALTER TABLESPACE temp ADD TEMPFILE '/u04/oradata/bscs9r1/temp_03.dbf' SIZE 8G AUTOEXTEND OFF;
ALTER TABLESPACE temp ADD TEMPFILE '/u04/oradata/bscs9r1/temp_04.dbf' SIZE 8G AUTOEXTEND OFF;
ALTER TABLESPACE temp ADD TEMPFILE '/u04/oradata/bscs9r1/temp_05.dbf' SIZE 8G AUTOEXTEND OFF;
ALTER TABLESPACE temp ADD TEMPFILE '/u04/oradata/bscs9r1/temp_06.dbf' SIZE 8G AUTOEXTEND OFF;
