GRANT DELETE ON "SYSADM"."PROFILE_SERVICE" TO "DTHIB";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "DTHIB";
 
GRANT DELETE ON "SYSADM"."PROFILE_SERVICE" TO "BSCS_ROLE";
 
GRANT INSERT ON "SYSADM"."PROFILE_SERVICE" TO "BSCS_ROLE";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BSCS_ROLE";
 
GRANT UPDATE ON "SYSADM"."PROFILE_SERVICE" TO "BSCS_ROLE";
 
GRANT INSERT ON "SYSADM"."PROFILE_SERVICE" TO "MUTROLE";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "MUTROLE";
 
GRANT UPDATE ON "SYSADM"."PROFILE_SERVICE" TO "MUTROLE";
 
GRANT DELETE ON "SYSADM"."PROFILE_SERVICE" TO "JAVASERVER";
 
GRANT INSERT ON "SYSADM"."PROFILE_SERVICE" TO "JAVASERVER";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "JAVASERVER";
 
GRANT UPDATE ON "SYSADM"."PROFILE_SERVICE" TO "JAVASERVER";
 
GRANT DELETE ON "SYSADM"."PROFILE_SERVICE" TO "INTERFACE";
 
GRANT INSERT ON "SYSADM"."PROFILE_SERVICE" TO "INTERFACE";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "INTERFACE" WITH GRANT OPTION;
 
GRANT UPDATE ON "SYSADM"."PROFILE_SERVICE" TO "INTERFACE";
 
GRANT ALTER ON "SYSADM"."PROFILE_SERVICE" TO "CMS_INTERFACE";
 
GRANT DELETE ON "SYSADM"."PROFILE_SERVICE" TO "CMS_INTERFACE";
 
GRANT INDEX ON "SYSADM"."PROFILE_SERVICE" TO "CMS_INTERFACE";
 
GRANT INSERT ON "SYSADM"."PROFILE_SERVICE" TO "CMS_INTERFACE";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "CMS_INTERFACE";
 
GRANT UPDATE ON "SYSADM"."PROFILE_SERVICE" TO "CMS_INTERFACE";
 
GRANT REFERENCES ON "SYSADM"."PROFILE_SERVICE" TO "CMS_INTERFACE";
 
GRANT ON COMMIT REFRESH ON "SYSADM"."PROFILE_SERVICE" TO "CMS_INTERFACE";
 
GRANT QUERY REWRITE ON "SYSADM"."PROFILE_SERVICE" TO "CMS_INTERFACE";
 
GRANT DEBUG ON "SYSADM"."PROFILE_SERVICE" TO "CMS_INTERFACE";
 
GRANT FLASHBACK ON "SYSADM"."PROFILE_SERVICE" TO "CMS_INTERFACE";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH005";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH020";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH142";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH327";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH143";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH006";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH017";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH027";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH044";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH092";
 
GRANT UPDATE ON "SYSADM"."PROFILE_SERVICE" TO "BATCH092";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH144";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH161";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH087";
 
GRANT UPDATE ON "SYSADM"."PROFILE_SERVICE" TO "BATCH087";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH088";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH098";
 
GRANT UPDATE ON "SYSADM"."PROFILE_SERVICE" TO "BATCH098";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH099";
 
GRANT UPDATE ON "SYSADM"."PROFILE_SERVICE" TO "BATCH099";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH101";
 
GRANT UPDATE ON "SYSADM"."PROFILE_SERVICE" TO "BATCH101";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH118";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH165";
 
GRANT UPDATE ON "SYSADM"."PROFILE_SERVICE" TO "BATCH165";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH166";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH167";
 
GRANT UPDATE ON "SYSADM"."PROFILE_SERVICE" TO "BATCH167";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH177";
 
GRANT UPDATE ON "SYSADM"."PROFILE_SERVICE" TO "BATCH177";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH178";
 
GRANT UPDATE ON "SYSADM"."PROFILE_SERVICE" TO "BATCH178";
 
GRANT INSERT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH299";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH299";
 
GRANT UPDATE ON "SYSADM"."PROFILE_SERVICE" TO "BATCH299";
 
GRANT SELECT ON "SYSADM"."PROFILE_SERVICE" TO "BATCH303";
 
GRANT UPDATE ON "SYSADM"."PROFILE_SERVICE" TO "BATCH303";
 
GRANT DELETE ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "DTHIB";
 
GRANT SELECT ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "DTHIB";
 
GRANT DELETE ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "BSCS_ROLE";
 
GRANT INSERT ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "BSCS_ROLE";
 
GRANT SELECT ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "BSCS_ROLE";
 
GRANT UPDATE ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "BSCS_ROLE";
 
GRANT INSERT ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "MUTROLE";
 
GRANT SELECT ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "MUTROLE";
 
GRANT UPDATE ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "MUTROLE";
 
GRANT DELETE ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "JAVASERVER";
 
GRANT INSERT ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "JAVASERVER";
 
GRANT SELECT ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "JAVASERVER";
 
GRANT UPDATE ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "JAVASERVER";
 
GRANT DELETE ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "INTERFACE";
 
GRANT INSERT ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "INTERFACE";
 
GRANT SELECT ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "INTERFACE";
 
GRANT UPDATE ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "INTERFACE";
 
GRANT SELECT ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "BATCH005";
 
GRANT SELECT ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "BATCH020";
 
GRANT SELECT ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "BATCH144";
 
GRANT INSERT ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "BATCH299";
 
GRANT SELECT ON "SYSADM"."PR_SERV_SPCODE_HIST" TO "BATCH299";
 
GRANT DELETE ON "SYSADM"."PR_SERV_STATUS_HIST" TO "DTHIB";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "DTHIB";
 
GRANT DELETE ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BSCS_ROLE";
 
GRANT INSERT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BSCS_ROLE";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BSCS_ROLE";
 
GRANT UPDATE ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BSCS_ROLE";
 
GRANT INSERT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "MUTROLE";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "MUTROLE";
 
GRANT UPDATE ON "SYSADM"."PR_SERV_STATUS_HIST" TO "MUTROLE";
 
GRANT DELETE ON "SYSADM"."PR_SERV_STATUS_HIST" TO "JAVASERVER";
 
GRANT INSERT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "JAVASERVER";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "JAVASERVER";
 
GRANT UPDATE ON "SYSADM"."PR_SERV_STATUS_HIST" TO "JAVASERVER";
 
GRANT DELETE ON "SYSADM"."PR_SERV_STATUS_HIST" TO "INTERFACE";
 
GRANT INSERT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "INTERFACE";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "INTERFACE" WITH GRANT OPTION;
 
GRANT UPDATE ON "SYSADM"."PR_SERV_STATUS_HIST" TO "INTERFACE";
 
GRANT ALTER ON "SYSADM"."PR_SERV_STATUS_HIST" TO "CMS_INTERFACE";
 
GRANT DELETE ON "SYSADM"."PR_SERV_STATUS_HIST" TO "CMS_INTERFACE";
 
GRANT INDEX ON "SYSADM"."PR_SERV_STATUS_HIST" TO "CMS_INTERFACE";
 
GRANT INSERT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "CMS_INTERFACE";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "CMS_INTERFACE";
 
GRANT UPDATE ON "SYSADM"."PR_SERV_STATUS_HIST" TO "CMS_INTERFACE";
 
GRANT REFERENCES ON "SYSADM"."PR_SERV_STATUS_HIST" TO "CMS_INTERFACE";
 
GRANT ON COMMIT REFRESH ON "SYSADM"."PR_SERV_STATUS_HIST" TO "CMS_INTERFACE";
 
GRANT QUERY REWRITE ON "SYSADM"."PR_SERV_STATUS_HIST" TO "CMS_INTERFACE";
 
GRANT DEBUG ON "SYSADM"."PR_SERV_STATUS_HIST" TO "CMS_INTERFACE";
 
GRANT FLASHBACK ON "SYSADM"."PR_SERV_STATUS_HIST" TO "CMS_INTERFACE";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH005";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH020";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH145";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH006";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH017";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH027";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH044";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH144";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH161";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH089";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH101";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH118";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH165";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH166";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH167";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH177";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH178";
 
GRANT INSERT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH299";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH299";
 
GRANT INSERT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH303";
 
GRANT SELECT ON "SYSADM"."PR_SERV_STATUS_HIST" TO "BATCH303";
