connect "SYS"/"&&sysPassword" as SYSDBA
set echo on
spool CreateDBFiles.log
CREATE SMALLFILE TABLESPACE "USERS" LOGGING DATAFILE '/ora/bscsdata20/BSCS9R1/oradata/users01.dbf' SIZE 512M REUSE AUTOEXTEND ON NEXT  512K MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;
ALTER DATABASE DEFAULT TABLESPACE "USERS";
spool off
