CREATE	TABLESPACE fidelio DATAFILE '/ora/bscsdata00/BSCS9MIG/bscs9dev/oradata/fidelio_01.dbf' SIZE 20G AUTOEXTEND OFF
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
CREATE	TABLESPACE i_interface DATAFILE '/ora/bscsdata01/BSCS9MIG/bscs9dev/oradata/indx_01.dbf' SIZE 20G AUTOEXTEND OFF
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
