CREATE	TABLESPACE d_interface DATAFILE '/ora/bscsdata04/BSCS9MIG/bscs9dev/oradata/d_interface_01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 8G
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
CREATE	TABLESPACE i_interface DATAFILE '/ora/bscsdata04/BSCS9MIG/bscs9dev/oradata/i_interface_01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 8G
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
