CREATE	TABLESPACE d_data DATAFILE '/ora/bscsdata00/BSCS9MIG/bscs9tst/oradata/d_data_01.dbf' SIZE 30G AUTOEXTEND OFF
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
CREATE	TABLESPACE i_data DATAFILE '/ora/bscsdata00/BSCS9MIG/bscs9tst/oradata/i_data_01.dbf' SIZE 24G AUTOEXTEND OFF
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
--CREATE	TABLESPACE prepaid_data DATAFILE '/ora/bscsdata00/BSCS9MIG/bscs9tst/oradata/prepaid_data_01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 16G
--EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
--CREATE	TABLESPACE prepaid_ndx DATAFILE '/ora/bscsdata00/BSCS9MIG/bscs9tst/oradata/prepaid_ndx_01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 16G
--EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
