CREATE OR REPLACE DIRECTORY backup_dir AS '/u10/backup';

CREATE USER backup
IDENTIFIED BY tir34man
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT EXP_FULL_DATABASE, CREATE TABLE, CREATE SESSION TO backup;

ALTER USER backup QUOTA UNLIMITED ON users;

GRANT READ, WRITE ON DIRECTORY backup_dir TO backup;
