
--- Remote Public Synonyms in RTX  

--- Public_synonyms_rtx_to_bscs.sql

CREATE PUBLIC SYNONYM APP_MODULES FOR "PUBLIC".APP_MODULES@RTX_TO_BSCS_LINK;

CREATE PUBLIC SYNONYM BSCSPROJECT FOR "PUBLIC".BSCSPROJECT@RTX_TO_BSCS_LINK;

CREATE PUBLIC SYNONYM FUP_ACCOUNTS_HEAD FOR "PUBLIC".FUP_ACCOUNTS_HEAD@RTX_TO_BSCS_LINK;

CREATE PUBLIC SYNONYM FUP_ACCOUNTS_HIST FOR "PUBLIC".FUP_ACCOUNTS_HIST@RTX_TO_BSCS_LINK;

CREATE PUBLIC SYNONYM FUP_ACCOUNTS_IMP FOR "PUBLIC".FUP_ACCOUNTS_IMP@RTX_TO_BSCS_LINK;

CREATE PUBLIC SYNONYM FUP_ACCOUNT_EXP FOR "PUBLIC".FUP_ACCOUNT_EXP@RTX_TO_BSCS_LINK;

CREATE PUBLIC SYNONYM GEN_UDR_SERV FOR "PUBLIC".GEN_UDR_SERV@RTX_TO_BSCS_LINK;

CREATE PUBLIC SYNONYM PREPAID_TRANSACT_TYPE FOR "PUBLIC".PREPAID_TRANSACT_TYPE@RTX_TO_BSCS_LINK;

CREATE PUBLIC SYNONYM RLH_MPUFDTAB FOR "PUBLIC".MPUFDTAB@RTX_TO_BSCS_LINK;

CREATE PUBLIC SYNONYM RLH_MPUUBTAB FOR "PUBLIC".MPUUBTAB@RTX_TO_BSCS_LINK;

CREATE PUBLIC SYNONYM UDS_TABLES FOR "PUBLIC".UDS_TABLES@RTX_TO_BSCS_LINK;