SELECT  UDC.UDS_CONTEXT_KEY
       ,UDIV.COLUMN_NAME
       ,UDIV.UDS_MEMBER_DES || ' - ' || UDIV.UDS_ELEMENT_DES COLUMN_COMMENT
       ,UDEV.DATA_TYPE_CODE
       ,UDEV.STRING_LENGTH
       ,UDSI.UDS_ORDER
FROM    (
	select  UDE.UDS_ELEMENT_CODE
       ,UDE.UDS_ELEMENT_NAME
       ,NVL( UDE.UDS_ELEMENT_DES, UDE.UDS_ELEMENT_NAME )
       ,DAC.DATA_CLASS_ID
       ,DAC.DESCRIPTION
       ,DAC.DATA_CLASS_TYPE
       ,DAT.DATA_TYPE_ID
       ,DAT.DATA_TYPE_CODE
       ,DAT.DESCRIPTION
       ,UDE.STRING_LENGTH
       ,DAT.REFERENCE_VALUE_TYPE
from    UDS_ELEMENT UDE
       ,DATA_CLASS DAC
       ,DATA_TYPE  DAT
where   UDE.DATA_CLASS_ID = DAC.DATA_CLASS_ID
and     DAC.DATA_TYPE_ID = DAT.DATA_TYPE_ID
	) UDEV
       ,UDS_STORAGE_ITEM UDSI
       ,UDS_CONTEXT      UDC
       ,
	(
SELECT
     UDS_ITEM.UDS_MEMBER_CODE,
     NVL( UDS_MEMBER.UDS_MEMBER_DES, UDS_MEMBER.UDS_MEMBER_NAME),
     UDS_ITEM.UDS_ELEMENT_CODE,
     NVL( UDS_ELEMENT.UDS_ELEMENT_DES, UDS_ELEMENT.UDS_ELEMENT_NAME),
     UDS_ITEM.UDS_TYPE_CODE,
     UDS_ITEM.COLUMN_NAME,
     UDS_MEMBER.UDS_NODE_CODE
   FROM
     UDS_ITEM,
     UDS_MEMBER,
     UDS_ELEMENT
   WHERE
     UDS_ITEM.UDS_MEMBER_CODE = UDS_MEMBER.UDS_MEMBER_CODE
   AND UDS_ELEMENT.UDS_ELEMENT_CODE = UDS_ITEM.UDS_ELEMENT_CODE
	)    UDIV
WHERE   UDC.UDS_STORAGE_ID = UDSI.UDS_STORAGE_ID
  AND   UDEV.UDS_ELEMENT_CODE = UDIV.UDS_ELEMENT_CODE
  AND   UDIV.UDS_MEMBER_CODE = UDSI.UDS_MEMBER_CODE
  AND   UDIV.UDS_ELEMENT_CODE = UDSI.UDS_ELEMENT_CODE

