SELECT	US.UDS_NODE_NAME COLUMN_NAME ,
	'INTEGER' DATA_TYPE ,
	TO_NUMBER(NULL) STRING_LENGTH,
	1 UDS_ORDER ,
	US.UDS_NODE_DES COLUMN_COMMENT 
FROM	UDS_STRUCTURE US START WITH UDS_NODE_CODE =(SELECT ROOT_PART FROM 
  UDS_VARIANT UV ,UDS_STORAGE UST ,UDS_CONTEXT UC WHERE UST.UDS_VARIANT_CODE =
   UV.UDS_VARIANT_CODE AND UST.UDS_STORAGE_ID = UC.UDS_STORAGE_ID AND 
  UC.UDS_CONTEXT_KEY = :B1 ) CONNECT BY PRIOR UDS_NODE_CODE = 
  UDS_PARENT_NODE_CODE UNION SELECT COLUMN_NAME ,DATA_TYPE ,STRING_LENGTH ,
  UDS_ORDER ,COLUMN_COMMENT FROM UDS_TABLE_LAYOUT_VIEW WHERE UDS_CONTEXT_KEY =
   :B1 ORDER BY UDS_ORDER, COLUMN_NAME

