VAR num_errors NUMBER;

BEGIN
DBMS_REDEFINITION.CAN_REDEF_TABLE
	(
	'SYSADM',
	'CONTRACT_HISTORY',
	DBMS_REDEFINITION.CONS_USE_PK
	);
END;
/

CREATE	TABLE sysadm.int_contract_history
	(
	co_id		NUMBER(38) NOT NULL,
	ch_seqno	NUMBER(38) NOT NULL,
	ch_status	VARCHAR2(1) NOT NULL,
	ch_reason	NUMBER(38) NOT NULL,
	ch_validfrom	DATE,
	ch_pending	VARCHAR2(1),
	entdate		DATE,
	userlastmod	VARCHAR2(16),
	request		NUMBER(38),
	rec_version	NUMBER(38) NOT NULL
	)
PARTITION BY RANGE( co_id )
	(
	PARTITION contract_history_1 VALUES LESS THAN (140000),
	PARTITION contract_history_2 VALUES LESS THAN (280000),
	PARTITION contract_history_3 VALUES LESS THAN (450000),
	PARTITION contract_history_4 VALUES LESS THAN (6500000),
	PARTITION contract_history_5 VALUES LESS THAN (10500000),
	PARTITION contract_history_6 VALUES LESS THAN (16000000),
	PARTITION contract_history_7 VALUES LESS THAN (21000000),
	PARTITION contract_history_8 VALUES LESS THAN (28000000),
	PARTITION contract_history_9 VALUES LESS THAN (34200000),
	PARTITION contract_history_10 VALUES LESS THAN (39500000),
	PARTITION contract_history_11 VALUES LESS THAN (41540000),
	PARTITION contract_history_12 VALUES LESS THAN (48540000),
	PARTITION contract_history_13 VALUES LESS THAN (55540000),
	PARTITION contract_history_14 VALUES LESS THAN (58540000),
	PARTITION contract_history_15 VALUES LESS THAN (61540000),
	PARTITION contract_history_16 VALUES LESS THAN (MAXVALUE)
	)
TABLESPACE d_bscs_contract
INITRANS 16
NOLOGGING;

BEGIN
DBMS_REDEFINITION.START_REDEF_TABLE
	(
	'SYSADM',
	'CONTRACT_HISTORY',
	'INT_CONTRACT_HISTORY',
	col_mapping => NULL,
	options_flag => DBMS_REDEFINITION.CONS_USE_PK
	);
END;
/

CREATE	UNIQUE INDEX sysadm.int_pkcontract_history
ON	sysadm.int_contract_history
	(
	co_id,
	ch_seqno
	)
TABLESPACE i_bscs_contract;
INITRANS 16
NOLOGGING
LOCAL;

BEGIN
DBMS_REDEFINITION.COPY_TABLE_DEPENDENTS
	(
	'SYSADM',
	'CONTRACT_HISTORY',
	'INT_CONTRACT_HISTORY',
	DBMS_REDEFINITION.CONS_ORIG_PARAMS,
	TRUE,
	TRUE,
	TRUE,
	TRUE,
	:num_errors
	);
END;
/

BEGIN
DBMS_REDEFINITION.SYNC_INTERIM_TABLE
	(
	'SYSADM',
	'CONTRACT_HISTORY',
	'INT_CONTRACT_HISTORY'
	);
END;
/

BEGIN
DBMS_REDEFINITION.FINISH_REDEF_TABLE
	(
	'SYSADM',
	'CONTRACT_HISTORY',
	'INT_CONTRACT_HISTORY'
	);
END;
/

DROP	TABLE sysadm.int_contract_history
CASCADE	CONSTRAINTS;

ALTER	INDEX sysadm.int_pkcontract_history
RENAME	TO pk_contract_history;
