CREATE	TABLESPACE d_interface DATAFILE '/ora/bscsdata01/BSCS9MIG/bscs9gld/oradata/d_interface_01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 8G
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
CREATE	TABLESPACE i_interface DATAFILE '/ora/bscsdata01/BSCS9MIG/bscs9gld/oradata/i_interface_01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 8G
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
