CREATE	TABLESPACE d_data DATAFILE '/ora/bscsdata01/BSCS9MIG/bscs9gld/oradata/d_data_01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 24G
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
CREATE	TABLESPACE i_data DATAFILE '/ora/bscsdata01/BSCS9MIG/bscs9gld/oradata/i_data_01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 24G
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
CREATE	TABLESPACE prepaid_data DATAFILE '/ora/bscsdata01/BSCS9MIG/bscs9gld/oradata/prepaid_data_01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 16G
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
CREATE	TABLESPACE prepaid_ndx DATAFILE '/ora/bscsdata01/BSCS9MIG/bscs9gld/oradata/prepaid_ndx_01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 16G
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
