connect "SYS"/"&&sysPassword" as SYSDBA
set echo on
spool /export/home/admin/RTX9R1/scripts/CreateDBFiles.log
CREATE SMALLFILE TABLESPACE "USERS" LOGGING DATAFILE '/ora/rtxadmin01/RTX9R1/users01.dbf' SIZE 50M REUSE AUTOEXTEND ON MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL SEGMENT SPACE MANAGEMENT  AUTO;
ALTER DATABASE DEFAULT TABLESPACE "USERS";
spool off
