CONNECT "sys"/"&&SYSpASSWORD" AS sysdbA
set echo on
spool /export/home/admin/RTX9R1/scripts/CreateDB.log
startup nomount pfile="/export/home/admin/RTX9R1/scripts/init.ora";
CREATE DATABASE "RTX9R1"
MAXINSTANCES 8
MAXLOGHISTORY 1
MAXLOGFILES 16
MAXLOGMEMBERS 3
MAXDATAFILES 100
DATAFILE '/ora/rtxadmin00/RTX9R1/system01.dbf' SIZE 1G REUSE AUTOEXTEND OFF
EXTENT MANAGEMENT LOCAL
SYSAUX DATAFILE '/ora/rtxadmin00/RTX9R1/sysaux01.dbf' SIZE 350M REUSE AUTOEXTEND OFF
SMALLFILE DEFAULT TEMPORARY TABLESPACE TEMP TEMPFILE '/ora/rtxdata00/RTX9R1/temp01.dbf' SIZE 1G REUSE AUTOEXTEND OFF
SMALLFILE UNDO TABLESPACE "UNDOTBS1" DATAFILE '/ora/rtxdata00/RTX9R1/undotbs01.dbf' SIZE 1G REUSE AUTOEXTEND OFF
CHARACTER SET WE8ISO8859P1
NATIONAL CHARACTER SET AL16UTF16
LOGFILE GROUP 1 ('/ora/rtxadmin01/RTX9R1/redo01a.log','/ora/rtxadmin02/RTX9R1/redo01b.log') SIZE 3500M,
GROUP 2 ('/ora/rtxadmin02/RTX9R1/redo02a.log','/ora/rtxadmin03/RTX9R1/redo02b.log') SIZE 3500M,
GROUP 3 ('/ora/rtxadmin03/RTX9R1/redo03a.log','/ora/rtxadmin01/RTX9R1/redo03b.log') SIZE 3500M
USER SYS IDENTIFIED BY "&&sysPassword" USER SYSTEM IDENTIFIED BY "&&systemPassword";
spool off
