CREATE	TABLESPACE d_interface DATAFILE '/ora/bscsdata02/BSCS9MIG/bscs9int/oradata/d_interface_01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 8G
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
CREATE	TABLESPACE i_interface DATAFILE '/ora/bscsdata02/BSCS9MIG/bscs9int/oradata/i_interface_01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 8G
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
