CREATE	TABLESPACE d_data DATAFILE '/ora/bscsdata02/BSCS9MIG/bscs9int/oradata/d_data_01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 24G
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
CREATE	TABLESPACE i_data DATAFILE '/ora/bscsdata02/BSCS9MIG/bscs9int/oradata/i_data_01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 24G
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
CREATE	TABLESPACE prepaid_data DATAFILE '/ora/bscsdata02/BSCS9MIG/bscs9int/oradata/prepaid_data_01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 16G
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
CREATE	TABLESPACE prepaid_ndx DATAFILE '/ora/bscsdata02/BSCS9MIG/bscs9int/oradata/prepaid_ndx_01.dbf' SIZE 2G AUTOEXTEND ON MAXSIZE 16G
EXTENT	MANAGEMENT LOCAL AUTOALLOCATE;
