@b_etl_stg01.sql
@b_etl_stg02.sql
@d_bscs_big.sql
@d_bscs_billing.sql
@d_bscs_contract.sql
@d_bscs_customer.sql
@d_bscs_small.sql
@d_bscs_tiny.sql
@d_interface.sql
@d_prepaid.sql
@i_bscs_big.sql
@i_bscs_billing.sql
@i_bscs_contract.sql
@i_bscs_customer.sql
@i_bscs_small.sql
@i_bscs_tiny.sql
@i_interface.sql
@i_prepaid.sql
@temp_migr.sql
@undotbs.sql
